# Generated by Django 3.1.7 on 2021-03-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('surname', models.CharField(max_length=65, verbose_name='Surname')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('url', models.URLField(verbose_name='URL')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
