# Generated by Django 3.1.7 on 2021-03-08 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebook',
            name='address_city',
            field=models.CharField(default=1, max_length=255, verbose_name='Address_city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonebook',
            name='address_country',
            field=models.CharField(default=1, max_length=255, verbose_name='Address_country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonebook',
            name='address_street',
            field=models.CharField(default=1, max_length=255, verbose_name='Address_street'),
            preserve_default=False,
        ),
    ]
