# Generated by Django 3.1.7 on 2021-03-08 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0002_auto_20210308_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonebook',
            name='address',
        ),
    ]
